comment = "nightly_SOMpp_ms-frameopt_msgc_inttag"

[executors]
som = "/home/pd/yk-benchmarks-nighlty/workspace/SOMpp_ms-frameopt_msgc_inttag/cmake-build/SOM++"

[suite_env.awfy]
SOM_LIB = "/home/pd/yk-benchmarks-nighlty/workspace/SOMpp_ms-frameopt_msgc_inttag/Smalltalk"
