proc_execs = 1
inproc_iters = 3

[executors]
yksompp = "${SOMPP}"

[suites.awfy]
dir = "suites/awfy/SOM"
harness = "../../../haste_harness_som.sh"
env = { "SOM_LIB" = "${SOM_LIB}" }

# [suites.awfy.benchmarks.DeltaBlue]
# extra_args = ["1200"]

# [suites.awfy.benchmarks.Json]
# extra_args = ["10"]

[suites.awfy.benchmarks.List]
extra_args = ["150"]

# [suites.awfy.benchmarks.Mandelbrot]
# extra_args = ["50"]

[suites.awfy.benchmarks.Towers]
extra_args = ["60"]

# [suites.awfy.benchmarks.Bounce]
# extra_args = ["150"]

# [suites.awfy.benchmarks.Richards]
# extra_args = ["10"]

# [suites.awfy.benchmarks.Permute]
# extra_args = ["100"]

# [suites.awfy.benchmarks.Queens]
# extra_args = ["100"]

# [suites.awfy.benchmarks.Storage]
# extra_args = ["100"]

# [suites.awfy.benchmarks.Sieve]
# extra_args = ["300"]

# [suites.awfy.benchmarks.CD]
# extra_args = ["25"]

# [suites.awfy.benchmarks.Havlak]
# extra_args = ["150"]

# [suites.awfy.benchmarks.NBody]
# extra_args = ["250000"]

